#!/bin/bash

# Echo the syncthing ID to the terminal
#echo < syncthingID.txt
if [ ! -d /data/syncthingHome ]; then
	mkdir -p /data/syncthingHome
fi
if [ ! -f /data/syncthingHome/config.xml ]; then
	/syncthing/syncthing -generate="/data/syncthingHome"
	sed -i 's/127.0.0.1/0.0.0.0/g' /data/syncthingHome/config.xml
fi
/syncthing/syncthing -home="/data/syncthingHome" &
#Set the root password as root if not set as an ENV variable
export PASSWD=${PASSWD:=root}
#Set the root password
echo "root:$PASSWD" | chpasswd

cd src && python main.py &

#Spawn dropbear
dropbear -E -F
