#!/bin/bash

# Echo the syncthing ID to the terminal
echo < syncthingID.txt
/syncthing/syncthing -home="/syncthing/syncthingHome" &

#Set the root password as root if not set as an ENV variable
export PASSWD=${PASSWD:=root}
#Set the root password
echo "root:$PASSWD" | chpasswd
#Spawn dropbear
dropbear -E -F
